import type { Metadata } from "next";
import { Geist, Geist_Mono, Caveat, Inter } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const caveat = Caveat({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
  variable: "--font-caveat",
});
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${caveat.variable}
          ${inter.variable}
          antialiased
        `}
      >
        {children}
        <div className="fixed bottom-0 left-0 right-0 z-[99] h-[100px] w-full pointer-events-none" aria-hidden="true">
          <div className="absolute inset-0 z-[70] [backdrop-filter:blur(1px)] [-webkit-backdrop-filter:blur(1px)] [mask:linear-gradient(rgba(0,0,0,0),rgba(0,0,0,1)_10%,rgba(0,0,0,1)_30%,rgba(0,0,0,0)_40%)]" />
          <div className="absolute inset-0 z-[60] [backdrop-filter:blur(2px)] [-webkit-backdrop-filter:blur(2px)] [mask:linear-gradient(rgba(0,0,0,0)_10%,rgba(0,0,0,1)_20%,rgba(0,0,0,1)_40%,rgba(0,0,0,0)_50%)]" />
          <div className="absolute inset-0 z-[50] [backdrop-filter:blur(4px)] [-webkit-backdrop-filter:blur(4px)] [mask:linear-gradient(rgba(0,0,0,0)_15%,rgba(0,0,0,1)_30%,rgba(0,0,0,1)_50%,rgba(0,0,0,0)_60%)]" />
          <div className="absolute inset-0 z-[40] [backdrop-filter:blur(8px)] [-webkit-backdrop-filter:blur(8px)] [mask:linear-gradient(rgba(0,0,0,0)_20%,rgba(0,0,0,1)_40%,rgba(0,0,0,1)_60%,rgba(0,0,0,0)_70%)]" />
          <div className="absolute inset-0 z-[30] [backdrop-filter:blur(16px)] [-webkit-backdrop-filter:blur(16px)] [mask:linear-gradient(rgba(0,0,0,0)_40%,rgba(0,0,0,1)_60%,rgba(0,0,0,1)_80%,rgba(0,0,0,0)_90%)]" />
          <div className="absolute inset-0 z-[20] [backdrop-filter:blur(32px)] [-webkit-backdrop-filter:blur(32px)] [mask:linear-gradient(rgba(0,0,0,0)_60%,rgba(0,0,0,1)_80%)]" />
          <div className="absolute inset-0 z-[10] [backdrop-filter:blur(64px)] [-webkit-backdrop-filter:blur(64px)] [mask:linear-gradient(rgba(0,0,0,0)_70%,rgba(0,0,0,1)_100%)]" />
          <div className="absolute inset-0 bg-[linear-gradient(transparent,rgba(255,255,255,0.9))]" />
        </div>
      </body>
    </html>
  );
}
