import type { Metadata } from "next";
import { Geist, Geist_Mono, Caveat, Inter } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const caveat = Caveat({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
  variable: "--font-caveat",
});
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${caveat.variable}
          ${inter.variable}
          antialiased
        `}
      >
        {children}
        <div className="fixed bottom-0 left-0 z-30 w-full flex items-end justify-center pointer-events-none">
          <div className="absolute inset-x-0 -top-6 h-10 bg-linear-to-t  to-transparent blur-xl"
          />
          <div
            className="w-full h-50 backdrop-saturate-150"
            style={{
               background: `
              linear-gradient(
        to top,
        rgba(255,255,255,0.95) 0%,
        rgba(255,255,255,0.6) 35%,
        rgba(255,255,255,0.25) 60%,
        rgba(255,255,255,0.1) 80%,
        transparent 100%
      )
    `,
      maskImage: `
        linear-gradient(
          to top,
          #000 0%,
          #000 40%,
          rgba(0,0,0,0.6) 65%,
          transparent 100%
        )
      `,
              
              backdropFilter: "blur(6px)", WebkitBackdropFilter: "blur(12px)" }}
            aria-hidden="true"
            
          />
        </div>
      </body>
    </html>
  );
}
